name: vpn-core

services:
  vpn-core:
    image: elyerr/vpn-core:latest
    restart: always
    privileged: true
    ports:
      - "8021:8000/tcp"
      - "51820-51850:51820-51850/udp"
    volumes:
      - data:/app/config
      - .env:/app/.env
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - UVICORN_WORKERS=4 
    networks:
      - public-net

volumes:
  data:

networks:
  public-net:
    driver: bridge
