name: vpn-core-dev

services:
  vpn-core:
    image: elyerr/vpn-core:dev
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ulimits:
      nofile:
        soft: 51200
        hard: 51200
    env_file:
      - .env
    ports:
       - "50051:50051/tcp"
       - "51820-51850:51820-51850/udp"
       - "1080:1080/tcp" 
    volumes:
      - data:/app/config
      - .env:/app/.env
      - .env:/usr/share/server/.env
      - database:/app/data
      - ./ssl:/ssl #
    command: sh -c "/usr/local/bin/start.sh"
    networks:
      - public-net
volumes:
  data:
  database:

networks:
  public-net:
    driver: bridge