version: "3.9"

services:
  vpn-core:
    image: elyerr/vpn-core:dev
    container_name: vpn-core
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      net.ipv4.ip_forward: 1
    ports:
      - "8021:8000"
      - "51820:51850/udp"
    volumes:
      - vpn-core-data:/app/config
      - .env:/app/.env
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - UVICORN_WORKERS=4 
    networks:
      - vpn-core-public-net

volumes:
  vpn-core-data:

networks:
  vpn-core-public-net:
    driver: bridge